version: '3'
services:
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.17.0
    user: root
    container_name: metricbeat
    # configs:
    #   - source: mb_config
    #     target: /usr/share/metricbeat/metricbeat.yml:ro
    volumes:
      - ./metricbeat-config.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    # environment:
    #   - ELASTICSEARCH_HOST=localhost:9200
    #   - KIBANA_HOST=localhost:5601
    network_mode: "host"
    command: "--strict.perms=false -e"

# configs:
#   mb_config:
#     file: ./metricbeat.docker.yml
